// Auto-generated from starter-templates/*.md by scripts/generate-starter-templates.mjs.
// Do not edit this file by hand — edit the markdown source and re-run
// `pnpm build` (or `pnpm dev`) to regenerate.

export interface StarterTemplate {
  filename: string;
  content: string;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    filename: "1on1.md",
    content: "---\nname: 1on1\ndescription: 1:1 meeting summary — context, themes, decisions, follow-ups\nicon: users\nhotkey: null\nprovider: null\noutput: new-file\noutput_filename: \"{date}-1on1-{slug}\"\n---\n\n# Instruction\n\nYou will receive raw notes from a 1:1 conversation. Rewrite them with the\nsections below. Keep the language of the raw memo. If a section has no\ncontent in the source, write \"(none)\".\n\n## Participants\n\nTwo people. Name + role/team if inferable.\n\n## Themes\n\nThe topics that actually came up — not what was scheduled. Two to four\nshort bullets, each a one-sentence summary of what was discussed.\n\n## Decisions\n\nBullet list of any decisions made. Skip if pure conversation.\n\n## Action items\n\n- [ ] task — Owner (due date if mentioned)\n\n## Watch items\n\nThings that are not yet decisions but should be revisited. Concerns, risks,\nor proposals that need follow-up.\n\n## Tone / signal\n\nOne or two sentences on the emotional or relational signal of the\nconversation. Helpful when reviewing relationship over time.\n",
  },
  {
    filename: "brainstorm.md",
    content: "---\nname: brainstorm\ndescription: Brainstorm cleanup — cluster ideas, surface themes, propose next steps\nicon: lightbulb\nhotkey: null\nprovider: null\noutput: append\n---\n\n# Instruction\n\nYou will receive a scattered list of ideas. Cluster them, name the clusters,\nand surface what looks promising. Preserve the language of the raw memo.\n\n## Themes\n\nGroup the ideas into 3-6 themes. For each theme: a short name + the ideas\nthat belong, one per bullet. Quote phrases verbatim when distinctive.\n\n## Strong candidates\n\nTwo to three ideas that stand out — by novelty, feasibility, or fit. One\nsentence each on why.\n\n## Open questions\n\nBullets of questions raised by the brainstorm. These help direct further\nresearch.\n\n## Next steps\n\n- [ ] task — Owner (optional)\n",
  },
  {
    filename: "daily-memo.md",
    content: "---\nname: daily-memo\ndescription: Free-form daily notes — cleaned up, grouped, with action surface\nicon: calendar\nhotkey: null\nprovider: null\noutput: append\n---\n\n# Instruction\n\nYou will receive a free-form daily memo — fragmented bullets, partial\nthoughts, scattered tasks. Rewrite them into a clean daily log. Preserve\nthe language of the raw memo.\n\n## Highlights\n\nThree to five bullets capturing what mattered today. Order by importance,\nnot chronology.\n\n## By topic\n\nGroup remaining notes under headings inferred from the content. Each group\ngets 1-3 lines.\n\n## Action items\n\n- [ ] task — Owner (due date if mentioned)\n\n## Open questions\n\nBullets of unresolved questions that surfaced. These often become tomorrow's\nagenda items.\n\n## Closed loops\n\nAnything completed or resolved today, briefly.\n",
  },
  {
    filename: "decision-record.md",
    content: "---\nname: decision-record\ndescription: ADR-style decision record — context, decision, alternatives, consequences\nicon: gavel\nhotkey: null\nprovider: null\noutput: new-file\noutput_filename: \"{date}-decision-{slug}\"\n---\n\n# Instruction\n\nYou will receive notes from a discussion where a decision was made. Rewrite\nthem as an Architecture Decision Record (ADR). Preserve the language of the\nraw memo.\n\n## Context\n\nTwo to four sentences. What forced this decision? What constraints, deadlines,\nor prior commitments shaped it?\n\n## Decision\n\nState the decision in one or two declarative sentences. Plain language.\n\n## Alternatives considered\n\nBulleted list. Each item: the alternative + why it was rejected. Be specific.\n\n## Consequences\n\n- **Positive**: what this enables.\n- **Negative**: what costs or risks are accepted.\n- **Open**: what is now newly uncertain.\n\n## Follow-ups\n\n- [ ] task — Owner (due date if mentioned)\n\n## Sources\n\nIf raw notes referenced specific documents / meetings / people, list them.\n",
  },
  {
    filename: "meeting-minutes.md",
    content: "---\nname: meeting-minutes\ndescription: Standard meeting minutes — participants, discussion, decisions, action items\nicon: clipboard-list\nhotkey: null\nprovider: null\noutput: new-file\noutput_filename: \"{date}-{slug}\"\n---\n\n# Instruction\n\nYou will receive raw meeting notes. Rewrite them as proper meeting minutes\nusing the structure below. Preserve the language of the raw memo (do not\ntranslate). If a section has no content in the source, write \"(none)\" — do\nnot invent.\n\n## Participants\n\nList every person mentioned. For each: name, role / team in parentheses\nif inferable from the context, otherwise just the name.\n\n## Key discussion\n\nTwo to four short paragraphs covering the main topics. Stay factual; do\nnot editorialize. Quote distinctive phrases when they carry meaning.\n\n## Decisions\n\nBullet list. Each item names what was actually decided — not what was merely\ndiscussed. If alternatives were considered, the bullet can briefly note them\n(\"A over B because ...\").\n\n## Action items\n\n- [ ] task — Owner (due date if mentioned)\n\n## Key takeaways\n\nTwo to three non-obvious observations. Things that are implied by the\ndiscussion but were not stated explicitly. Useful for future review.\n",
  },
];
